const $=s=>document.querySelector(s); const uid=()=>crypto.randomUUID();
const DEFAULT_FOLDERS=[['Kişisel','📁'],['Kimlik Belgeleri','🪪'],['Ev','🏠'],['Araba','🚗'],['Sigorta','🛡️'],['Finans','💳'],['Sözleşmeler','📜'],['Garanti','📦']];
const KEY='aslan-arsiv-state-v1'; const FILEKEY='aslan-arsiv-files-v1';
let state=JSON.parse(localStorage.getItem(KEY)||'null')||{folders:DEFAULT_FOLDERS.map(([name,icon])=>({id:uid(),name,icon,parentId:null})),docs:[],favorites:[],theme:'dark'};
let files=JSON.parse(localStorage.getItem(FILEKEY)||'{}'); // dataURL storage for small/medium docs
function save(){localStorage.setItem(KEY,JSON.stringify(state));localStorage.setItem(FILEKEY,JSON.stringify(files));}
function esc(s){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function folderById(id){return state.folders.find(f=>f.id===id)}
function pathOf(id){const arr=[];let cur=folderById(id);while(cur){arr.unshift(cur.name);cur=cur.parentId?folderById(cur.parentId):null}return arr.join(' → ')}
function children(parentId=null){return state.folders.filter(f=>(f.parentId||null)===(parentId||null))}
function docsInFolder(folderId){return state.docs.filter(d=>d.folderId===folderId)}
function docView(d){return `<button class="doc" data-doc="${d.id}"><img class="thumb" src="${d.thumb||'assets/icon-180.png'}"><div class="docInfo"><div class="docName">${esc(d.name)}</div><div class="docPath">${esc(pathOf(d.folderId)||'Arşiv kökü')} · ${new Date(d.createdAt).toLocaleDateString('tr-TR')}</div></div><div class="star">${state.favorites.includes(d.id)?'★':'☆'}</div></button>`}
function renderHome(){
  const roots=children();
  $('#mainView').innerHTML=`<section class="hero"><h1>Belgelerin güvende.</h1><p>Tara, kaydet, istediğin anda bul.</p></section>
  <label class="searchBox">⌕<input id="homeSearch" placeholder="Belgelerde ara..." autocomplete="off"></label>
  <div class="sectionHead"><h2>Klasörlerim</h2><button class="linkBtn" id="newFolderTop">+ Klasör</button></div>
  <div class="grid">${roots.map(f=>`<button class="folder" data-folder="${f.id}"><div class="folderIcon">${esc(f.icon)}</div><div class="folderName">${esc(f.name)}</div><div class="folderCount">${state.docs.filter(d=>isInTree(d.folderId,f.id)).length} belge</div></button>`).join('')}</div>
  ${recentDocs().length?`<div class="sectionHead"><h2>Son Belgeler</h2></div><div class="docList">${recentDocs().map(docView).join('')}</div>`:''}`;
  $('#homeSearch').addEventListener('input',e=>renderSearch(e.target.value));
  $('#newFolderTop').onclick=openFolderForm;
  document.querySelectorAll('[data-folder]').forEach(b=>b.onclick=()=>openFolder(b.dataset.folder));
  document.querySelectorAll('[data-doc]').forEach(b=>b.onclick=()=>openDoc(b.dataset.doc));
}
function isInTree(folderId,rootId){if(folderId===rootId)return true;let f=folderById(folderId);while(f?.parentId){if(f.parentId===rootId)return true;f=folderById(f.parentId)}return false}
function recentDocs(){return [...state.docs].sort((a,b)=>b.createdAt-a.createdAt).slice(0,5)}
function renderSearch(query=''){
  const q=query.trim().toLocaleLowerCase('tr'); const results=q?state.docs.filter(d=>d.name.toLocaleLowerCase('tr').includes(q)):recentDocs();
  $('#mainView').innerHTML=`<section class="hero"><h1>Arama</h1><p>Belge adını yaz, tüm klasörlerde ara.</p></section>
  <label class="searchBox">⌕<input id="searchInput" value="${esc(query)}" placeholder="Belge adı ara..." autocomplete="off"></label>
  <div class="resultTitle">${q?results.length+' sonuç bulundu':'Son eklenen belgeler'}</div><div class="docList" style="margin-top:8px">${results.length?results.map(docView).join(''):`<div class="empty"><strong>Belge bulunamadı</strong>Başka bir belge adı deneyin.</div>`}</div>`;
  $('#searchInput').focus(); $('#searchInput').addEventListener('input',e=>renderSearch(e.target.value)); document.querySelectorAll('[data-doc]').forEach(b=>b.onclick=()=>openDoc(b.dataset.doc));
}
function renderFavorites(){const ds=state.docs.filter(d=>state.favorites.includes(d.id));$('#mainView').innerHTML=`<section class="hero"><h1>Favoriler</h1><p>Hızlı erişmek istediğin belgeler.</p></section><div class="docList">${ds.length?ds.map(docView).join(''):`<div class="empty"><strong>Henüz favori yok</strong>Bir belgeyi favorilere eklediğinde burada görünecek.</div>`}</div>`;document.querySelectorAll('[data-doc]').forEach(b=>b.onclick=()=>openDoc(b.dataset.doc));}
function renderSettings(){ $('#mainView').innerHTML=`<section class="hero"><h1>Ayarlar</h1><p>Aslan Arşiv</p></section><div class="settingsCard"><div class="settingsRow"><div>Uygulama dili<br><span>Türkçe</span></div><b>TR</b></div><div class="settingsRow"><div>Uygulama kilidi<br><span>Face ID için ileride native sürümde açılabilir.</span></div><b>—</b></div><div class="settingsRow"><div>Veri<br><span>${state.docs.length} belge · ${state.folders.length} klasör</span></div><button class="linkBtn" id="exportBtn">Dışa Aktar</button></div><div class="settingsRow"><div>Hakkında<br><span>Bu uygulama Batuhan Aslan tarafından oluşturulup geliştirilmiştir.</span></div><b>🦁</b></div></div>`;$('#exportBtn').onclick=exportBackup;}
function setTab(t){document.querySelectorAll('.navBtn').forEach(b=>b.classList.toggle('active',b.dataset.tab===t));if(t==='home')renderHome();if(t==='search')renderSearch('');if(t==='favorites')renderFavorites();if(t==='settings')renderSettings();}
document.querySelectorAll('.navBtn').forEach(b=>b.onclick=()=>setTab(b.dataset.tab));$('#settingsBtn').onclick=()=>setTab('settings');$('#addBtn').onclick=openAddSheet;
function openModal(html){$('#modal').innerHTML=`<div class="sheet">${html}</div>`;$('#modal').classList.remove('hidden');$('#modal').onclick=e=>{if(e.target=== $('#modal'))closeModal()}} function closeModal(){$('#modal').classList.add('hidden');$('#modal').innerHTML=''}
function openAddSheet(){openModal(`<h3>Belge Ekle</h3><div class="sheetRow"><button class="choice" id="scanChoice">📷<b>Kamera ile Tara</b><span>Yeni belge tarayın</span></button><button class="choice" id="pickChoice">🖼️<b>Fotoğraflardan / Dosyalardan</b><span>iPhone dosyalarını seçin</span></button><button class="choice" id="folderChoice">📁<b>Yeni Klasör</b><span>Arşiv yapınızı oluşturun</span></button></div>`);$('#scanChoice').onclick=startCamera;$('#pickChoice').onclick=pickFiles;$('#folderChoice').onclick=openFolderForm;}
function openFolderForm(parentId=null){closeModal();openModal(`<h3>${parentId?'Alt Klasör Oluştur':'Yeni Klasör'}</h3><div class="form"><label class="label">Klasör adı</label><input class="input" id="folderName" placeholder="Örneğin: Seyahat"><label class="label">Simge</label><input class="input" id="folderIcon" value="📁"><button class="primary" id="saveFolder">Oluştur</button><button class="secondary" id="cancelFolder">İptal</button></div>`);$('#saveFolder').onclick=()=>{const name=$('#folderName').value.trim();if(!name)return;state.folders.push({id:uid(),name,icon:$('#folderIcon').value.trim()||'📁',parentId});save();closeModal();toast('Klasör oluşturuldu');renderHome()};$('#cancelFolder').onclick=closeModal;}
function openFolder(id){const f=folderById(id);const kids=children(id);const ds=docsInFolder(id);openModal(`<h3>${esc(f.name)}</h3><div class="sectionHead"><h2>Alt klasörler</h2><button class="linkBtn" id="subFolder">+ Ekle</button></div><div class="grid">${kids.map(k=>`<button class="folder" data-kid="${k.id}"><div class="folderIcon">${esc(k.icon)}</div><div class="folderName">${esc(k.name)}</div><div class="folderCount">${state.docs.filter(d=>isInTree(d.folderId,k.id)).length} belge</div></button>`).join('')}</div>${kids.length?'':'<div class="empty" style="margin-bottom:10px">Alt klasör yok.</div>'}<div class="sectionHead"><h2>Belgeler</h2></div><div class="docList">${ds.length?ds.map(docView).join(''):`<div class="empty"><strong>Bu klasör boş</strong>＋ düğmesinden belge ekleyebilirsin.</div>`}</div><div class="sheetRow" style="margin-top:14px"><button class="secondary" id="renameFolder">Yeniden Adlandır</button><button class="secondary danger" id="deleteFolder">Sil</button></div>`);$('#subFolder').onclick=()=>openFolderForm(id);$('#renameFolder').onclick=()=>renameFolder(id);$('#deleteFolder').onclick=()=>deleteFolder(id);document.querySelectorAll('[data-kid]').forEach(b=>b.onclick=()=>openFolder(b.dataset.kid));document.querySelectorAll('[data-doc]').forEach(b=>b.onclick=()=>openDoc(b.dataset.doc));}
function renameFolder(id){closeModal();openModal(`<h3>Klasörü Yeniden Adlandır</h3><div class="form"><input class="input" id="rename" value="${esc(folderById(id).name)}"><button class="primary" id="doRename">Kaydet</button></div>`);$('#doRename').onclick=()=>{const n=$('#rename').value.trim();if(!n)return;folderById(id).name=n;save();closeModal();toast('Klasör adı değiştirildi');renderHome()}}
function deleteFolder(id){if(state.docs.some(d=>isInTree(d.folderId,id))||children(id).length){toast('Önce klasörün içini boşaltın');return}state.folders=state.folders.filter(f=>f.id!==id);save();closeModal();toast('Klasör silindi');renderHome()}
function pickFiles(){$('#filePicker').click();closeModal()}
$('#filePicker').addEventListener('change',async e=>{const list=[...e.target.files];for(const file of list){await importFile(file)}e.target.value='';renderHome()});
async function importFile(file,dataOverride=null,thumbOverride=null){const data=dataOverride||await fileToDataURL(file);let folder=children()[0]; if(!folder){const id=uid();folder={id,name:'Kişisel',icon:'📁',parentId:null};state.folders.push(folder)}const name=(file.name||'Belge').replace(/\.[^.]+$/,'');const id=uid();files[id]={data,type:file.type||'application/octet-stream'};state.docs.push({id,name,folderId:folder.id,type:file.type||'',pages:file.type==='application/pdf'?null:1,createdAt:Date.now(),thumb:thumbOverride||((file.type||'').startsWith('image/')?data:'assets/icon-180.png')});save();toast('Belge eklendi')}
const fileToDataURL=f=>new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>res(r.result);r.onerror=rej;r.readAsDataURL(f)});
async function startCamera(){closeModal();if(!navigator.mediaDevices?.getUserMedia){toast('Bu tarayıcı kameraya erişemiyor');return}let stream;openModal(`<h3>Belge Tara</h3><div class="cameraWrap"><video id="cameraVideo" class="cameraVideo" playsinline autoplay></video><div class="scanFrame"></div></div><div class="cameraControls"><button class="secondary" id="cancelCam">İptal</button><span class="smallGold">Yüksek çözünürlük</span><button class="shutter" id="shutter"></button></div>`);try{stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'},width:{ideal:3840},height:{ideal:2160}},audio:false});const v=$('#cameraVideo');v.srcObject=stream;await v.play();$('#cancelCam').onclick=()=>{stream.getTracks().forEach(t=>t.stop());closeModal()};$('#shutter').onclick=()=>captureFrame(v,stream)}catch(e){closeModal();toast('Kamera izni verilmedi veya kamera kullanılamıyor')}}
async function captureFrame(video,stream){const canvas=document.createElement('canvas');canvas.width=video.videoWidth||1920;canvas.height=video.videoHeight||1080;const ctx=canvas.getContext('2d',{willReadFrequently:true});ctx.drawImage(video,0,0,canvas.width,canvas.height);enhance(canvas);const data=canvas.toDataURL('image/jpeg',0.96);stream.getTracks().forEach(t=>t.stop());openSaveScan(data)}
function enhance(canvas){const ctx=canvas.getContext('2d');const img=ctx.getImageData(0,0,canvas.width,canvas.height);const d=img.data;let mean=0;for(let i=0;i<d.length;i+=4)mean+=(0.2126*d[i]+0.7152*d[i+1]+0.0722*d[i+2]);mean/=d.length/4;const gain=Math.max(.85,Math.min(1.35,155/Math.max(90,mean)));for(let i=0;i<d.length;i+=4){for(let c=0;c<3;c++){let v=(d[i+c]-128)*gain+128;d[i+c]=Math.max(0,Math.min(255,v))}}ctx.putImageData(img,0,0)}
function openSaveScan(dataURL){const folderOptions=state.folders.map(f=>`<option value="${f.id}">${esc(pathOf(f.id))}</option>`).join('');openModal(`<h3>Taramayı Kaydet</h3><img class="preview" src="${dataURL}"><div class="form" style="margin-top:12px"><label class="label">Belge adı</label><input class="input" id="scanName" value="Yeni Belge"><label class="label">Klasör</label><select class="input" id="scanFolder">${folderOptions}</select><button class="primary" id="saveScan">PDF olarak kaydet</button><button class="secondary" id="retake">Tekrar Tara</button></div>`);$('#saveScan').onclick=async()=>{const id=uid(),name=$('#scanName').value.trim()||'Yeni Belge',folderId=$('#scanFolder').value;const pdf=makeImagePdf([dataURL]);files[id]={data:pdf,type:'application/pdf'};state.docs.push({id,name,folderId,type:'application/pdf',pages:1,createdAt:Date.now(),thumb:dataURL});save();closeModal();toast('PDF kaydedildi');renderHome()};$('#retake').onclick=startCamera}
// High-quality JPEG-in-PDF encoder. Keeps original JPEG bytes and page resolution metadata.
function jpegSize(dataURL){const b=atob(dataURL.split(',')[1]);let i=2;while(i<b.length){if(b.charCodeAt(i)!==0xFF){i++;continue}const marker=b.charCodeAt(i+1),len=(b.charCodeAt(i+2)<<8)|b.charCodeAt(i+3);if([0xC0,0xC1,0xC2,0xC3,0xC5,0xC6,0xC7,0xC9,0xCA,0xCB,0xCD,0xCE,0xCF].includes(marker))return {h:(b.charCodeAt(i+5)<<8)|b.charCodeAt(i+6),w:(b.charCodeAt(i+7)<<8)|b.charCodeAt(i+8)};i+=2+len}return {w:1240,h:1754}}
function dataUrlBytes(dataURL){const bin=atob(dataURL.split(',')[1]);const out=new Uint8Array(bin.length);for(let i=0;i<bin.length;i++)out[i]=bin.charCodeAt(i);return out}
function strBytes(s){return new TextEncoder().encode(s)}
function concatBytes(chunks){let total=0;for(const c of chunks)total+=c.length;const out=new Uint8Array(total);let o=0;for(const c of chunks){out.set(c,o);o+=c.length}return out}
function makeImagePdf(images){
 const objects=[];const addObj=(body,stream=null)=>{objects.push({body,stream});return objects.length};
 const imageIds=[];
 for(const img of images){const bytes=dataUrlBytes(img),d=jpegSize(img);imageIds.push(addObj(`<< /Type /XObject /Subtype /Image /Width ${d.w} /Height ${d.h} /ColorSpace /DeviceRGB /BitsPerComponent 8 /Filter /DCTDecode /Length ${bytes.length} >>`,bytes))}
 const contentIds=[];for(let i=0;i<images.length;i++){const c=`q\n595 0 0 842 0 0 cm\n/Im${i+1} Do\nQ\n`;contentIds.push(addObj(`<< /Length ${strBytes(c).length} >>`,strBytes(c)))}
 const pagesPlaceholder=objects.length+1,pageIds=[];
 for(let i=0;i<images.length;i++) pageIds.push(addObj(`<< /Type /Page /Parent ${pagesPlaceholder} 0 R /MediaBox [0 0 595 842] /Resources << /XObject << /Im${i+1} ${imageIds[i]} 0 R >> >> /Contents ${contentIds[i]} 0 R >>`));
 const pagesId=addObj(`<< /Type /Pages /Kids [${pageIds.map(x=>x+' 0 R').join(' ')}] /Count ${pageIds.length} >>`),catalogId=addObj(`<< /Type /Catalog /Pages ${pagesId} 0 R >>`);
 const chunks=[strBytes('%PDF-1.4\n%\xE2\xE3\xCF\xD3\n')];const exact=[0];let pos=chunks[0].length;
 for(let n=1;n<=objects.length;n++){const o=objects[n-1];const body=o.body.replaceAll(String(pagesPlaceholder),String(pagesId));exact[n]=pos;const head=strBytes(`${n} 0 obj\n${body}\n`);chunks.push(head);pos+=head.length;if(o.stream){const a=strBytes('stream\n'),b=strBytes('\nendstream\nendobj\n');chunks.push(a,o.stream,b);pos+=a.length+o.stream.length+b.length}else{const e=strBytes('endobj\n');chunks.push(e);pos+=e.length}}
 const xrefStart=pos;let x=`xref\n0 ${objects.length+1}\n0000000000 65535 f \n`;for(let n=1;n<=objects.length;n++)x+=String(exact[n]).padStart(10,'0')+' 00000 n \n';x+=`trailer\n<< /Size ${objects.length+1} /Root ${catalogId} 0 R >>\nstartxref\n${xrefStart}\n%%EOF`;chunks.push(strBytes(x));return 'data:application/pdf;base64,'+uint8ToBase64(concatBytes(chunks))
}
function uint8ToBase64(bytes){let binary='';for(let i=0;i<bytes.length;i+=0x8000)binary+=String.fromCharCode(...bytes.subarray(i,i+0x8000));return btoa(binary)}
function openDoc(id){const d=state.docs.find(x=>x.id===id);if(!d)return;const file=files[id];openModal(`<h3>${esc(d.name)}</h3><div class="form"><div class="settingsRow"><div>Konum<br><span>${esc(pathOf(d.folderId))}</span></div><b>${d.pages||'—'} sayfa</b></div><div class="sheetRow"><button class="secondary" id="favDoc">${state.favorites.includes(id)?'★ Favoriden Çıkar':'☆ Favorilere Ekle'}</button><button class="secondary" id="renameDoc">Yeniden Adlandır</button></div><button class="primary" id="viewDoc">Belgeyi Aç</button><button class="secondary" id="shareDoc">Paylaş / İndir</button><button class="secondary danger" id="deleteDoc">Sil</button></div>`);$('#favDoc').onclick=()=>{state.favorites=state.favorites.includes(id)?state.favorites.filter(x=>x!==id):[...state.favorites,id];save();closeModal();renderFavorites()};$('#renameDoc').onclick=()=>renameDoc(id);$('#viewDoc').onclick=()=>openViewer(id);$('#shareDoc').onclick=()=>downloadDoc(id);$('#deleteDoc').onclick=()=>{state.docs=state.docs.filter(x=>x.id!==id);delete files[id];state.favorites=state.favorites.filter(x=>x!==id);save();closeModal();toast('Belge silindi');renderHome()}}
function renameDoc(id){closeModal();openModal(`<h3>Belgeyi Yeniden Adlandır</h3><div class="form"><input class="input" id="docNewName" value="${esc(state.docs.find(d=>d.id===id).name)}"><button class="primary" id="doDocRename">Kaydet</button></div>`);$('#doDocRename').onclick=()=>{const n=$('#docNewName').value.trim();if(!n)return;state.docs.find(d=>d.id===id).name=n;save();closeModal();toast('Belge adı değiştirildi');renderHome()}}
function openViewer(id){const f=files[id];if(!f){toast('Belge verisi bulunamadı');return}const src=f.data;openModal(`<h3>${esc(state.docs.find(d=>d.id===id).name)}</h3><iframe src="${src}" style="width:100%;height:65vh;border:0;border-radius:14px;background:#fff"></iframe><button class="secondary" id="viewerClose" style="margin-top:10px">Kapat</button>`);$('#viewerClose').onclick=closeModal}
function downloadDoc(id){const d=state.docs.find(x=>x.id===id),f=files[id];if(!f)return;const a=document.createElement('a');a.href=f.data;a.download=`${d.name}.pdf`;a.click();toast('Dosya indiriliyor')}
function exportBackup(){const blob=new Blob([JSON.stringify({state,files})],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='aslan-arsiv-yedek.json';a.click();URL.revokeObjectURL(url);toast('Yedek oluşturuldu')}
function toast(t){$('#toast').textContent=t;$('#toast').classList.remove('hidden');setTimeout(()=>$('#toast').classList.add('hidden'),2200)}
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));
renderHome();
