
const app=document.getElementById("app");
const DBN="aslan-arsiv-files", META="aslan-arsiv-state";
let db,state={folders:[],docs:[],tab:"home",folder:null,query:""};

const uid=p=>p+"_"+crypto.randomUUID(), now=()=>new Date().toISOString();
const esc=s=>String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]));
const date=s=>new Date(s).toLocaleDateString("tr-TR");
function openDB(){return new Promise((ok,no)=>{let r=indexedDB.open(DBN,1);r.onupgradeneeded=e=>e.target.result.createObjectStore("files");r.onsuccess=()=>{db=r.result;ok()};r.onerror=()=>no(r.error)})}
function put(k,b){return new Promise((ok,no)=>{let t=db.transaction("files","readwrite");t.objectStore("files").put(b,k);t.oncomplete=ok;t.onerror=()=>no(t.error)})}
function get(k){return new Promise((ok,no)=>{let r=db.transaction("files").objectStore("files").get(k);r.onsuccess=()=>ok(r.result);r.onerror=()=>no(r.error)})}
function del(k){return new Promise((ok,no)=>{let t=db.transaction("files","readwrite");t.objectStore("files").delete(k);t.oncomplete=ok;t.onerror=()=>no(t.error)})}
function persist(){localStorage.setItem(META,JSON.stringify({folders:state.folders,docs:state.docs}))}
function load(){try{let x=JSON.parse(localStorage.getItem(META)||"");state.folders=x.folders||[];state.docs=x.docs||[];if(!state.folders.length)throw 0}catch{seed()}}
function seed(){state.folders=["Kişisel","Kimlik Belgeleri","Ev","Araba","Sigorta","Finans","Sözleşmeler","Garanti"].map(n=>({id:uid("f"),name:n,parentId:null,icon:"📁"}));state.docs=[];persist()}
function folder(id){return state.folders.find(x=>x.id===id)} function children(id){return state.folders.filter(x=>x.parentId===id)}
function folderPath(id){let a=[],x=folder(id),n=0;while(x&&n++<100){a.unshift(x.name);x=folder(x.parentId)}return a.join(" › ")}
function idsUnder(id){let a=[id];for(let i=0;i<a.length;i++)children(a[i]).forEach(x=>a.push(x.id));return a}
function docsAt(id){return state.docs.filter(d=>d.folderId===id)}

function folderHTML(f){let c=idsUnder(f.id).reduce((n,i)=>n+docsAt(i).length,0);return `<div class="folder" data-folder="${f.id}"><button class="dots" data-menu="${f.id}">⋯</button><div class="icon">${esc(f.icon||"📁")}</div><div class="name">${esc(f.name)}</div><div class="count">${c} belge</div></div>`}
function docHTML(d){return `<div class="doc" data-doc="${d.id}"><div class="thumb"></div><div class="di"><div class="dn">${esc(d.name)}</div><div class="dp">${esc(folderPath(d.folderId))}</div><div class="dd">${date(d.createdAt)}</div></div><button class="star" data-star="${d.id}">${d.favorite?"★":"☆"}</button></div>`}
function bind(root){root.querySelectorAll("[data-folder]").forEach(e=>e.onclick=x=>{if(x.target.closest("[data-menu]"))return;state.folder=e.dataset.folder;state.tab="home";render()});root.querySelectorAll("[data-menu]").forEach(e=>e.onclick=x=>{x.stopPropagation();folderMenu(e.dataset.menu)});root.querySelectorAll("[data-doc]").forEach(e=>e.onclick=x=>{if(x.target.closest("[data-star]"))return;viewDoc(e.dataset.doc)});root.querySelectorAll("[data-star]").forEach(e=>e.onclick=x=>{x.stopPropagation();let d=state.docs.find(z=>z.id===e.dataset.star);d.favorite=!d.favorite;persist();render()})}

function render(){
  app.innerHTML=`<div class="app"><header><div class="brand"><img src="./assets/icon-180.png"><div><div class="bn">ASLAN ARŞİV</div><div class="bs">Kişisel belge arşivin</div></div></div><button class="icon-btn" id="set" style="border:1px solid #292929;background:#121212;border-radius:13px;width:42px;height:42px;color:#e8d7ae">⚙︎</button></header><main><section id="home" style="display:${state.tab==="home"?"block":"none"}"></section><section id="search" style="display:${state.tab==="search"?"block":"none"}"></section><section id="fav" style="display:${state.tab==="favorites"?"block":"none"}"></section><section id="settings" style="display:${state.tab==="settings"?"block":"none"}"></section></main><button class="fab" id="fab">＋</button><nav>${["home","search","favorites","settings"].map((t,i)=>`<button class="tab ${state.tab===t?"active":""}" data-tab="${t}"><b>${["⌂","⌕","☆","⚙"][i]}</b>${["Ana Sayfa","Ara","Favoriler","Ayarlar"][i]}</button>`).join("")}</nav><div id="modals"></div></div>`;
  renderHome();renderSearch();renderFav();renderSettings();
  app.querySelectorAll("[data-tab]").forEach(x=>x.onclick=()=>{state.tab=x.dataset.tab;state.folder=null;render()});
  app.querySelector("#fab").onclick=()=>addDialog(state.folder);app.querySelector("#set").onclick=()=>{state.tab="settings";state.folder=null;render()}
}
function renderHome(){
 let e=$("#home"), roots=state.folders.filter(x=>!x.parentId), recent=[...state.docs].sort((a,b)=>b.createdAt.localeCompare(a.createdAt)).slice(0,5);
 if(state.folder){let f=folder(state.folder);e.innerHTML=`<div class="section"><button class="link" id="back">‹ Geri</button><h2>${esc(f.name)}</h2><button class="link" id="addSub">＋ Alt klasör</button></div><div class="section"><button class="link" id="ren">✎ Adını değiştir</button><button class="link" id="addHere">＋ Belge</button></div><div class="grid">${children(f.id).map(folderHTML).join("")||`<div class="empty" style="grid-column:1/-1">Alt klasör yok.</div>`}</div><div class="section"><h2>Belgeler</h2></div><div class="docs">${docsAt(f.id).map(docHTML).join("")||`<div class="empty">Bu klasörde henüz belge yok.</div>`}</div>`;
  e.querySelector("#back").onclick=()=>{state.folder=f.parentId||null;render()};e.querySelector("#addSub").onclick=()=>folderDialog(f.id);e.querySelector("#ren").onclick=()=>folderDialog(f.parentId,f.id);e.querySelector("#addHere").onclick=()=>addDialog(f.id);bind(e);return;
 }
 e.innerHTML=`<div class="search"><span>⌕</span><input id="quickSearch" placeholder="Belgelerde ara..." value="${esc(state.query)}"></div><div class="stat-row"></div><div class="section"><h2>Klasörlerim</h2><button class="link" id="newF">＋ Klasör</button></div><div class="grid">${roots.map(folderHTML).join("")}</div><div class="section"><h2>Son belgeler</h2><button class="link" id="goSearch">Tümünü ara</button></div><div class="docs">${recent.map(docHTML).join("")||`<div class="empty">Henüz belge eklenmedi.</div>`}</div>`;
 e.querySelector("#quickSearch").oninput=x=>{state.query=x.target.value;state.tab="search";render()};e.querySelector("#newF").onclick=()=>folderDialog(null);e.querySelector("#goSearch").onclick=()=>{state.tab="search";render()};bind(e)
}
function renderSearch(){let e=$("#search"),q=state.query.trim().toLowerCase(),r=q?state.docs.filter(d=>d.name.toLowerCase().includes(q)):[...state.docs].sort((a,b)=>b.createdAt.localeCompare(a.createdAt));e.innerHTML=`<div class="section"><h2>Belge Ara</h2></div><div class="search"><span>⌕</span><input id="q" placeholder="Belge adını yaz..." value="${esc(state.query)}"><button id="clr" style="border:0;background:none;color:#aaa">✕</button></div><div style="font-size:11px;color:var(--muted);margin:8px 2px">${q?r.length+" sonuç bulundu":"Tüm belgeler"}</div><div class="docs">${r.map(docHTML).join("")||`<div class="empty">Belge bulunamadı.</div>`}</div>`;e.querySelector("#q").oninput=x=>{state.query=x.target.value;renderSearch()};e.querySelector("#clr").onclick=()=>{state.query="";renderSearch()};bind(e)}
function renderFav(){let e=$("#fav"),r=state.docs.filter(x=>x.favorite);e.innerHTML=`<div class="section"><h2>Favoriler</h2></div><div class="docs">${r.map(docHTML).join("")||`<div class="empty">Henüz favori belge yok.</div>`}</div>`;bind(e)}
function renderSettings(){let e=$("#settings");e.innerHTML=`<div class="section"><h2>Ayarlar</h2></div><div class="settings-card"><button class="settings-item" id="backup">Yedek dışa aktar<span>JSON</span></button><button class="settings-item" id="restore">Yedekten geri yükle<span>JSON</span></button><button class="settings-item" id="about">Hakkında<span>1.0</span></button><button class="settings-item" id="reset" style="color:#ff9999">Arşivi sıfırla<span>Dikkat</span></button></div><input id="restoreFile" type="file" accept="application/json" hidden><div style="text-align:center;color:var(--muted);font-size:12px;margin-top:18px">Bu uygulama <b style="color:#e3bf6b">Batuhan Aslan</b> tarafından oluşturulup geliştirilmiştir.</div>`;
 e.querySelector("#backup").onclick=backup;e.querySelector("#restore").onclick=()=>e.querySelector("#restoreFile").click();e.querySelector("#restoreFile").onchange=x=>restore(x.target.files[0]);e.querySelector("#about").onclick=about;e.querySelector("#reset").onclick=reset
}
function modal(html){$("#modals").innerHTML=`<div class="modal" id="mb"><div class="sheet">${html}</div></div>`;$("#mb").onclick=e=>{if(e.target.id==="mb")close()}}
function close(){$("#modals").innerHTML=""}
function folderDialog(parent,edit=null){let f=edit?folder(edit):null;modal(`<div class="grab"></div><h2>${edit?"Klasörü düzenle":"Yeni klasör"}</h2><div class="stack"><input id="fn" class="field" placeholder="Klasör adı" value="${esc(f?.name||"")}"><input id="fi" class="field" maxlength="3" value="${esc(f?.icon||"📁")}"><div class="row"><button class="btn" id="fc">İptal</button><button class="btn gold" id="fs">Kaydet</button></div></div>`);$("#fc").onclick=close;$("#fs").onclick=()=>{let n=$("#fn").value.trim();if(!n)return toast("Klasör adı gerekli.");let ic=$("#fi").value.trim()||"📁";if(edit){f.name=n;f.icon=ic}else state.folders.push({id:uid("f"),name:n,parentId:parent||null,icon:ic});persist();close();render()}}
function folderMenu(id){let f=folder(id);modal(`<div class="grab"></div><h2>${esc(f.name)}</h2><div class="stack"><button class="menu" id="r">✎ Yeniden adlandır</button><button class="menu" id="s">＋ Alt klasör ekle</button><button class="menu" id="d" style="color:#ff9696">🗑 Sil</button></div>`);$("#r").onclick=()=>{close();folderDialog(f.parentId,f.id)};$("#s").onclick=()=>{close();folderDialog(f.id)};$("#d").onclick=()=>{close();deleteFolder(id)}}
async function deleteFolder(id){let f=folder(id);if(!confirm(`"${f.name}" ve içindekiler silinsin mi?`))return;let ids=idsUnder(id);for(const d of state.docs.filter(x=>ids.includes(x.folderId))){await del(d.blobKey).catch(()=>{})}state.docs=state.docs.filter(x=>!ids.includes(x.folderId));state.folders=state.folders.filter(x=>!ids.includes(x.id));state.folder=null;persist();render()}
function folderOptions(sel){return state.folders.map(x=>`<option value="${x.id}" ${x.id===sel?"selected":""}>${esc(folderPath(x.id))}</option>`).join("")}
function addDialog(folderId){modal(`<div class="grab"></div><h2>Belge Ekle</h2><div class="stack"><button class="menu" id="cam">📷 Kamera ile Tara<br><small style="color:var(--muted)">Çok sayfalı yüksek çözünürlük</small></button><button class="menu" id="photo">🖼 Fotoğraflardan Ekle</button><button class="menu" id="file">📁 Dosyalardan Ekle</button></div>`);$("#cam").onclick=()=>{close();scanner(folderId)};$("#photo").onclick=()=>{close();pickImages(folderId)};$("#file").onclick=()=>{close();pickFiles(folderId)}}
function pickImages(fid){let i=document.createElement("input");i.type="file";i.accept="image/*";i.multiple=true;i.onchange=()=>filesToPDF([...i.files],fid);i.click()}
function pickFiles(fid){let i=document.createElement("input");i.type="file";i.accept="application/pdf,image/*";i.multiple=true;i.onchange=async()=>{for(const f of i.files){if(f.type==="application/pdf")await saveBlob(f,strip(f.name)||"Belge",fid);else await filesToPDF([f],fid)}render()};i.click()}
const strip=n=>n.replace(/\.[^.]+$/,"");
async function filesToPDF(files,fid){if(!files.length)return;modal(`<div class="grab"></div><h2>${files.length} sayfalı belge</h2><div class="stack"><input id="dn" class="field" value="${esc(strip(files[0].name)||"Yeni belge")}"><select id="df" class="field">${folderOptions(fid||state.folder||state.folders[0]?.id)}</select><button class="btn gold" id="saveP">PDF olarak kaydet</button></div>`);$("#saveP").onclick=async()=>{let n=$("#dn").value.trim()||"Yeni belge";let f=$("#df").value;close();toast("PDF hazırlanıyor…");let b=await imagesToPDF(files);await saveBlob(b,n,f,files[0]);render()}}
async function saveBlob(blob,name,fid,thumbSource){let key=uid("b"),tk=uid("t");await put(key,blob);if(thumbSource&&thumbSource.type.startsWith("image/")){let tb=await thumb(thumbSource);if(tb)await put(tk,tb)}state.docs.push({id:uid("d"),name:name.endsWith(".pdf")?name:name+".pdf",folderId:fid||state.folders[0].id,blobKey:key,thumbKey:thumbSource&&thumbSource.type.startsWith("image/")?tk:null,favorite:false,createdAt:now()});persist()}
function thumb(file){return new Promise(async r=>{try{let b=await createImageBitmap(file),c=document.createElement("canvas"),s=Math.min(1,360/b.width);c.width=b.width*s;c.height=b.height*s;c.getContext("2d").drawImage(b,0,0,c.width,c.height);c.toBlob(x=>r(x),"image/jpeg",.8)}catch{r(null)}})}
async function imagesToPDF(files){let pages=[];for(const f of files){let img=await image(f),c=document.createElement("canvas"),s=Math.min(1,3000/img.width);c.width=Math.round(img.width*s);c.height=Math.round(img.height*s);c.getContext("2d").drawImage(img,0,0,c.width,c.height);let b=await new Promise(r=>c.toBlob(r,"image/jpeg",.96));pages.push({b,w:c.width,h:c.height})}return makePDF(pages)}
function image(b){return new Promise((r,j)=>{let u=URL.createObjectURL(b),i=new Image();i.onload=()=>{URL.revokeObjectURL(u);r(i)};i.onerror=j;i.src=u})}
async function makePDF(pages){let parts=[],enc=new TextEncoder(),off=0,xref=[0];const add=x=>{let b=typeof x==="string"?enc.encode(x):x;parts.push(b);off+=b.length};add("%PDF-1.4\n%âãÏÓ\n");let n=1,ids=[];const reserve=()=>n++;let pagesObj=reserve(),cat=reserve();
for(let i=0;i<pages.length;i++){let p=pages[i],data=new Uint8Array(await p.b.arrayBuffer()),im=reserve();xref[im]=off;add(`${im} 0 obj\n<< /Type /XObject /Subtype /Image /Width ${p.w} /Height ${p.h} /ColorSpace /DeviceRGB /BitsPerComponent 8 /Filter /DCTDecode /Length ${data.length} >>\nstream\n`);add(data);add("\nendstream\nendobj\n");let pw=595,ph=842,scale=Math.min(555/p.w,802/p.h),w=p.w*scale,h=p.h*scale,x=(pw-w)/2,y=(ph-h)/2;let content=`q\n${w.toFixed(2)} 0 0 ${h.toFixed(2)} ${x.toFixed(2)} ${y.toFixed(2)} cm\n/I${i} Do\nQ\n`,cb=enc.encode(content),co=reserve();xref[co]=off;add(`${co} 0 obj\n<< /Length ${cb.length} >>\nstream\n`);add(cb);add("endstream\nendobj\n");let po=reserve();ids.push(po);xref[po]=off;add(`${po} 0 obj\n<< /Type /Page /Parent ${pagesObj} 0 R /MediaBox [0 0 ${pw} ${ph}] /Resources << /XObject << /I${i} ${im} 0 R >> >> /Contents ${co} 0 R >>\nendobj\n`)}
xref[pagesObj]=off;add(`${pagesObj} 0 obj\n<< /Type /Pages /Kids [${ids.map(i=>i+" 0 R").join(" ")}] /Count ${ids.length} >>\nendobj\n`);xref[cat]=off;add(`${cat} 0 obj\n<< /Type /Catalog /Pages ${pagesObj} 0 R >>\nendobj\n`);let start=off;add(`xref\n0 ${n}\n0000000000 65535 f \n`);for(let i=1;i<n;i++)add(`${String(xref[i]||0).padStart(10,"0")} 00000 n \n`);add(`trailer\n<< /Size ${n} /Root ${cat} 0 R >>\nstartxref\n${start}\n%%EOF`);return new Blob(parts,{type:"application/pdf"})}
async function scanner(fid){let c=document.createElement("div");c.className="camera";c.innerHTML=`<div class="chead"><button class="icon-btn" id="cx">✕</button><b>Belge Tara</b><button class="icon-btn" id="done">✓</button></div><div class="cwrap"><video id="vid" class="video" autoplay playsinline muted></video><div class="guide"></div></div><div class="cfoot"><button id="shot" class="capture"></button></div>`;document.body.appendChild(c);let video=$("#vid"),stream=null,pages=[];try{stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:"environment"},width:{ideal:3840},height:{ideal:2160}},audio:false});video.srcObject=stream}catch{toast("Kamera izni verilemedi.")}$("#shot").onclick=async()=>{if(!video.videoWidth)return toast("Kamera hazır değil.");let cc=document.createElement("canvas");cc.width=video.videoWidth;cc.height=video.videoHeight;cc.getContext("2d").drawImage(video,0,0);let b=await new Promise(r=>cc.toBlob(r,"image/jpeg",.98));pages.push(b);toast(pages.length+" sayfa eklendi")};$("#done").onclick=()=>{if(!pages.length)return toast("En az bir sayfa tarayın.");stream?.getTracks().forEach(t=>t.stop());c.remove();filesToPDF(pages,fid)};$("#cx").onclick=()=>{stream?.getTracks().forEach(t=>t.stop());c.remove()}}
async function viewDoc(id){let d=state.docs.find(x=>x.id===id),b=await get(d.blobKey);if(!b)return toast("Belge bulunamadı.");let u=URL.createObjectURL(b),v=document.createElement("div");v.className="viewer";v.innerHTML=`<div class="vhead"><button class="icon-btn" id="vc">‹</button><b style="max-width:55%;overflow:hidden;text-overflow:ellipsis;white-space:nowrap">${esc(d.name)}</b><button class="icon-btn" id="vm">⋯</button></div><div class="vbody"><iframe src="${u}"></iframe></div><div class="vfoot"><button class="btn" id="share">Paylaş</button><button class="btn" id="down">Kaydet</button></div>`;document.body.appendChild(v);$("#vc").onclick=()=>{URL.revokeObjectURL(u);v.remove()};$("#down").onclick=()=>download(b,d.name);$("#share").onclick=()=>{if(navigator.share){navigator.share({title:d.name,files:[new File([b],d.name,{type:"application/pdf"})]}).catch(()=>{})}else download(b,d.name)};$("#vm").onclick=()=>{modal(`<div class="grab"></div><h2>${esc(d.name)}</h2><div class="stack"><button class="menu" id="rf">${d.favorite?"☆ Favoriden çıkar":"★ Favorilere ekle"}</button><button class="menu" id="rn">✎ Yeniden adlandır</button><button class="menu" id="mv">📁 Taşı</button><button class="menu" id="dd" style="color:#ff9696">🗑 Sil</button></div>`);$("#rf").onclick=()=>{d.favorite=!d.favorite;persist();close();render();v.remove()};$("#rn").onclick=()=>{close();v.remove();renameDoc(d.id)};$("#mv").onclick=()=>{close();v.remove();moveDoc(d.id)};$("#dd").onclick=()=>{close();v.remove();deleteDoc(d.id)}}}
function renameDoc(id){let d=state.docs.find(x=>x.id===id);modal(`<div class="grab"></div><h2>Belgeyi yeniden adlandır</h2><div class="stack"><input id="nn" class="field" value="${esc(strip(d.name))}"><button class="btn gold" id="ns">Kaydet</button></div>`);$("#ns").onclick=()=>{let n=$("#nn").value.trim()||"Belge";d.name=n.endsWith(".pdf")?n:n+".pdf";persist();close();render()}}
function moveDoc(id){let d=state.docs.find(x=>x.id===id);modal(`<div class="grab"></div><h2>Belgeyi taşı</h2><div class="stack"><select id="mf" class="field">${folderOptions(d.folderId)}</select><button class="btn gold" id="ms">Taşı</button></div>`);$("#ms").onclick=()=>{d.folderId=$("#mf").value;persist();close();render()}}
async function deleteDoc(id){let d=state.docs.find(x=>x.id===id);if(!confirm(`"${d.name}" silinsin mi?`))return;await del(d.blobKey).catch(()=>{});state.docs=state.docs.filter(x=>x.id!==id);persist();render()}
function download(b,n){let u=URL.createObjectURL(b),a=document.createElement("a");a.href=u;a.download=n;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)}
async function backup(){let arr=[];for(const d of state.docs){let b=await get(d.blobKey);if(b)arr.push({meta:d,data:await dataURL(b)})};download(new Blob([JSON.stringify({folders:state.folders,docs:arr})],{type:"application/json"}),"aslan-arsiv-yedek.json")}
function dataURL(b){return new Promise(r=>{let f=new FileReader();f.onload=()=>r(f.result);f.readAsDataURL(b)})}
async function restore(file){if(!file)return;try{let x=JSON.parse(await file.text());for(const d of state.docs)await del(d.blobKey).catch(()=>{});state.folders=x.folders;state.docs=[];for(const it of x.docs){let res=it.data.split(","),bin=atob(res[1]),u=new Uint8Array(bin.length);for(let i=0;i<bin.length;i++)u[i]=bin.charCodeAt(i);let k=uid("b");await put(k,new Blob([u],{type:"application/pdf"}));state.docs.push({...it.meta,blobKey:k})}persist();render();toast("Yedek geri yüklendi.")}catch{toast("Yedek geçersiz.")}}
function about(){modal(`<div class="grab"></div><div style="text-align:center"><img src="./assets/icon-192.png" style="width:90px;border-radius:24px"><h2>ASLAN ARŞİV</h2><p style="color:var(--muted)">Kişisel belgelerinizi düzenli şekilde saklayın.</p><p style="color:#e2c178">Bu uygulama Batuhan Aslan tarafından oluşturulup geliştirilmiştir.</p><button class="btn gold" id="ac">Kapat</button></div>`);$("#ac").onclick=close}
async function reset(){if(!confirm("Tüm arşiv silinsin mi?"))return;for(const d of state.docs)await del(d.blobKey).catch(()=>{});seed();state.folder=null;render();toast("Arşiv sıfırlandı.")}
function toast(t){let x=document.createElement("div");x.className="toast";x.textContent=t;document.body.appendChild(x);setTimeout(()=>x.remove(),2200)}
function $(s){return document.querySelector(s)}

(async()=>{await openDB();load();render();if("serviceWorker"in navigator)navigator.serviceWorker.register("./sw.js").catch(()=>{})})()
